- name: this is a testing playbook
  hosts: all
  vars: 
  
  tasks:
   
    - name: Run Hello World
      shell: "echo 'Hello {{ username }}' "
      register: testing
      
    - debug:
        msg: "{{ testing.stdout }}"
